# Generated by Django 4.1.7 on 2023-03-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shorterURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=700)),
                ('shorter_url', models.CharField(max_length=100)),
                ('time_created', models.TimeField()),
            ],
        ),
    ]
