# Generated by Django 4.1.7 on 2023-03-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorterurl',
            name='time_created',
            field=models.DateTimeField(),
        ),
    ]
