# Generated by Django 4.1.7 on 2023-03-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_alter_shorterurl_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorterurl',
            name='visitas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shorterurl',
            name='original_url',
            field=models.TextField(),
        ),
    ]
