# Generated by Django 4.1.7 on 2023-03-30 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0004_alter_shorterurl_visitas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorterurl',
            old_name='visitas',
            new_name='visit_count',
        ),
    ]
