# Generated by Django 4.1.7 on 2023-03-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0005_rename_visitas_shorterurl_visit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorterurl',
            name='time_created',
        ),
    ]
