# Generated by Django 4.1.7 on 2023-03-31 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('url_app', '0006_remove_shorterurl_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorterurl',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
