# Generated by Django 4.1.7 on 2023-03-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0007_shorterurl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorterurl',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
