# Generated by Django 4.1.7 on 2023-03-31 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0008_alter_shorterurl_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorterurl',
            old_name='user',
            new_name='username',
        ),
    ]
